### ISSUE TITLE
Answer get cut in middle

### ISSUE THREAD

**Issue by takenek** [knrd1/chatgpt#10]
Example:

11:11 <@TaKeN> Zygmunt: opowiedz historie procesora intel 486.
11:11 < Zygmunt> Procesor Intel 486, znany jako Intel 486DX, był pierwszym procesorem 32-bitowym firmy Intel, który został wprowadzony na rynek w 1989 roku. Był on znaczącym osiągnięciem w historii procesorów, ponieważ wyposażony został w pierwszy układ zintegrowany z technologią superskalarną, która pozwalała na równoległe wykonywanie wielu rozkazów. Procesor miał też bardziej wydajny cykl zegara i koprocesor mat
11:11 < Zygmunt> ematyczny, był też lżejszy i mniejszy. Podczas gdy procesor miał tylko 8MB pamięci podręcznej, jego wydajność była wyższa niż w przypadku poprzedników.
11:11 < Zygmunt> Intel 486 stanowił ważny krok w procesorach te

And he say nothing else looks like he cut answer in middle.

Best Regards
TaKeN

**Comment by knrd1** [comment]
Duplicate of https://github.com/knrd1/chatgpt/issues/7
