### ISSUE TITLE
The connection keeps disconnecting....

### ISSUE THREAD

**Issue by gokturkyilmaz** [knrd1/chatgpt#18]
I am running the bot with SCREEN also tried with nohup, it's working well but after a few days (sometimes in 24hrs) bot is constantly disconnecting with a reason (Ping timeout: 120 seconds).

**Comment by knrd1** [comment]
Thanks, I'm aware of this, this will be fixed soon.

**Comment by knrd1** [comment]
This has been fixed, please pull the latest version.
