### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by takenek** [knrd1/chatgpt#2]
Hey,
If possible please create a config like: chatgpt-example.conf file because now when i use git pull to download newlatest release i need to configure again.

Best Regards
TaKeN

**Comment by takenek** [comment]
Like i say will be hard update to newlatest version:

root@radvd:~/chatgpt# git pull
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 26 (delta 15), reused 18 (delta 7), pack-reused 0
Rozpakowywanie obiektów: 100% (26/26), 2.55 KiB | 137.00 KiB/s, gotowe.
Z https://github.com/knrd1/chatgpt
f143682..b3b77f8  master     -> origin/master
Aktualizowanie f143682..b3b77f8
error: Scalenie nadpisałoby zmiany w następujących plikach:
chatgpt.py
Złóż swoje zmiany lub dodaj do schowka zanim je scalisz.
Przerywanie

Need do git stash and again git pull:
root@radvd:~/chatgpt# git stash
Zapisano katalog roboczy i stan indeksu WIP on master: f143682 initial commit
root@radvd:~/chatgpt# git pull
Aktualizowanie f143682..b3b77f8
Fast-forward .gitignore |  2 ++ 
README.md  | 17 ++++++++++------- 
chatgpt.py | 11 +++++++---- 
3 files changed, 19 insertions(+), 11 deletions(-) create mode 100644 .gitignore

Best Regards
TaKeN

**Comment by takenek** [comment]
Hello,
I ask chatgpt to create new version of this Python program with config file and he write this :-)

```
import configparser
import openai
import socket
import time

# Read configuration from file
config = configparser.ConfigParser()
config.read('chatgpt.conf')

# Set up OpenAI API key
openai.api_key = config.get('openai', 'api_key')

# Set up IRC connection settings
server = config.get('irc', 'server')
port = config.getint('irc', 'port')
channel = config.get('irc', 'channel')
nickname = config.get('irc', 'nickname')

# Connect to IRC server
irc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
irc.connect((server, port))
irc.send(bytes("USER " + nickname + " " + nickname + " " + nickname + " :ChatGPT\n", "UTF-8"))
irc.send(bytes("NICK " + nickname + "\n", "UTF-8"))
irc.send(bytes("JOIN " + channel + "\n", "UTF-8"))

# Listen for messages from users
while True:
    message = irc.recv(2048).decode("UTF-8")
    if message.find("PING") != -1:
        # Respond to server PING requests
        irc.send(bytes("PONG " + message.split()[1] + "\n", "UTF-8"))
    elif message.find("PRIVMSG " + channel + " :" + nickname + ":") != -1:
        question = message.split(nickname + ":")[1].strip()
        response = openai.Completion.create(
            engine="text-davinci-003",
            prompt="Q: " + question + "\nA:",
            temperature=0.8,
            max_tokens=500,
            top_p=1,
            frequency_penalty=0,
            presence_penalty=0
        )
        answers = [x.strip() for x in response.choices[0].text.strip().split('\n')]
        for answer in answers:
            while len(answer) > 0:
                irc.send(bytes("PRIVMSG " + channel + " :" + answer[:350] + "\n", "UTF-8"))
                answer = answer[350:]
    time.sleep(1)
```

Następnie możesz stworzyć plik konfiguracyjny chatgpt.conf i umieścić w nim następujące linie:

```
[openai]
api_key = sk-XXX

[irc]
server = polska.irc.pl
port = 6667
channel = #chatgpt
nickname = Chatgpt
```

Best Regards
TaKeN

**Comment by knrd1** [comment]
Solved. Thanks. I used this in my recent update. From now configuration is in separate file just like you suggested. Also, no need to replace anything manually.
