### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by moonlightz** [knrd1/chatgpt#21]
Is it still working for you, guys?
It stopped working at least since one week ago.
I tried to change the key and changing the model but all I can get is: API call failed. Try again later.
My RPi seemed to had a installation "fart", I had to use a clean up install. I moved from Raspbian 32-bit OS to 64-bit Raspberry PI OS, and also changed from bullseye to bookworm. Python3 is now version 3.11 which makes things more (less) enjoyable.

**Comment by moonlightz** [comment]
Ah... never mind... I had nohup to make thing to run in background but I didnt realise about this message:
Error: You exceeded your current quota, please check your plan and billing details.

I wonder how and where can I check the "quota". We been playing with the bot a bit for few days but we didn't abuse of it.

**Comment by moonlightz** [comment]
Maybe moving such message about quota to the irc channel would be nice. Just an idea.

**Comment by knrd1** [comment]
Hey, you can check your usage here: https://platform.openai.com/account/usage
Yeah I'm aware that "API call failed" is very vague message, I will implement printing the exact message on the channel, thanks!

**Comment by knrd1** [comment]
Improved error handling by printing the actual error message associated with the exception.
