### ISSUE TITLE
chatgpt cut a word in middle answer

### ISSUE THREAD

**Issue by takenek** [knrd1/chatgpt#7]
Example:
06:20 <@TaKeN> Zygmunt: co wiesz na temat piosenki Kylie Minogue - The Loco-Motion ?
06:20 < Zygmunt> "The Loco-Motion" to jedna z najbardziej znanych piosenek Kylie Minogue. Utwór został napisany przez Carole King i Gerry Goffin i wydany w 1962 roku jako singel dla Little Eva. Piosenka była wielokrotnie ponownie wydana, w tym w 1988 roku przez Kylie Minogue. Piosenka osiągnęła szczyty na listach przebojów w wielu krajach, w tym w Aust
06:20 < Zygmunt> ralii, Wielkiej Brytanii i Stanach Zjednoczonych.

Like You see he cut a word "Australii"
He say in one line Aust and another line ralii

Best Regards
TaKeN

**Comment by knrd1** [comment]
Yeah I noticed this. Will take care of it.

**Comment by knrd1** [comment]
Solved. Bot will look for nearest space character and move next word to next line.
